// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: proto/datafeed.proto

package datafeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type TradeType int32

const (
	TradeType_TRADE_TYPE_UNSPECIFIED TradeType = 0
	TradeType_TRADE_TYPE_BUY         TradeType = 1
	TradeType_TRADE_TYPE_SELL        TradeType = 2
)

// Enum value maps for TradeType.
var (
	TradeType_name = map[int32]string{
		0: "TRADE_TYPE_UNSPECIFIED",
		1: "TRADE_TYPE_BUY",
		2: "TRADE_TYPE_SELL",
	}
	TradeType_value = map[string]int32{
		"TRADE_TYPE_UNSPECIFIED": 0,
		"TRADE_TYPE_BUY":         1,
		"TRADE_TYPE_SELL":        2,
	}
)

func (x TradeType) Enum() *TradeType {
	p := new(TradeType)
	*p = x
	return p
}

func (x TradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datafeed_proto_enumTypes[0].Descriptor()
}

func (TradeType) Type() protoreflect.EnumType {
	return &file_proto_datafeed_proto_enumTypes[0]
}

func (x TradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeType.Descriptor instead.
func (TradeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{0}
}

type BoardType int32

const (
	BoardType_BOARD_TYPE_UNSPECIFIED BoardType = 0
	BoardType_BOARD_TYPE_RG          BoardType = 1 // Regular
	BoardType_BOARD_TYPE_TN          BoardType = 2 // Cash
	BoardType_BOARD_TYPE_NG          BoardType = 3 // Negotiated
)

// Enum value maps for BoardType.
var (
	BoardType_name = map[int32]string{
		0: "BOARD_TYPE_UNSPECIFIED",
		1: "BOARD_TYPE_RG",
		2: "BOARD_TYPE_TN",
		3: "BOARD_TYPE_NG",
	}
	BoardType_value = map[string]int32{
		"BOARD_TYPE_UNSPECIFIED": 0,
		"BOARD_TYPE_RG":          1,
		"BOARD_TYPE_TN":          2,
		"BOARD_TYPE_NG":          3,
	}
)

func (x BoardType) Enum() *BoardType {
	p := new(BoardType)
	*p = x
	return p
}

func (x BoardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datafeed_proto_enumTypes[1].Descriptor()
}

func (BoardType) Type() protoreflect.EnumType {
	return &file_proto_datafeed_proto_enumTypes[1]
}

func (x BoardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardType.Descriptor instead.
func (BoardType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{1}
}

// Supporting Messages
type Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value      float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Percentage float64 `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
}

func (x *Change) Reset() {
	*x = Change{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{0}
}

func (x *Change) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Change) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type RunningTrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebsocketTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=websocket_time,json=websocketTime,proto3" json:"websocket_time,omitempty"`
	Stock         string                 `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Volume        float64                `protobuf:"fixed64,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Action        TradeType              `protobuf:"varint,5,opt,name=action,proto3,enum=stockbit.datafeed.v1.TradeType" json:"action,omitempty"`
	IsGlobal      bool                   `protobuf:"varint,6,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	Change        *Change                `protobuf:"bytes,8,opt,name=change,proto3" json:"change,omitempty"`
	TradeNumber   int64                  `protobuf:"varint,9,opt,name=trade_number,json=tradeNumber,proto3" json:"trade_number,omitempty"`
	MarketBoard   BoardType              `protobuf:"varint,10,opt,name=market_board,json=marketBoard,proto3,enum=stockbit.datafeed.v1.BoardType" json:"market_board,omitempty"`
}

func (x *RunningTrade) Reset() {
	*x = RunningTrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTrade) ProtoMessage() {}

func (x *RunningTrade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTrade.ProtoReflect.Descriptor instead.
func (*RunningTrade) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{1}
}

func (x *RunningTrade) GetWebsocketTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WebsocketTime
	}
	return nil
}

func (x *RunningTrade) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *RunningTrade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RunningTrade) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *RunningTrade) GetAction() TradeType {
	if x != nil {
		return x.Action
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *RunningTrade) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *RunningTrade) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RunningTrade) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *RunningTrade) GetTradeNumber() int64 {
	if x != nil {
		return x.TradeNumber
	}
	return 0
}

func (x *RunningTrade) GetMarketBoard() BoardType {
	if x != nil {
		return x.MarketBoard
	}
	return BoardType_BOARD_TYPE_UNSPECIFIED
}

type RunningTradeBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trades []*RunningTrade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
}

func (x *RunningTradeBatch) Reset() {
	*x = RunningTradeBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningTradeBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTradeBatch) ProtoMessage() {}

func (x *RunningTradeBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTradeBatch.ProtoReflect.Descriptor instead.
func (*RunningTradeBatch) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{2}
}

func (x *RunningTradeBatch) GetTrades() []*RunningTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type LivePrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock  string                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Price  float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Change *Change                `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	Time   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *LivePrice) Reset() {
	*x = LivePrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivePrice) ProtoMessage() {}

func (x *LivePrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivePrice.ProtoReflect.Descriptor instead.
func (*LivePrice) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{3}
}

func (x *LivePrice) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *LivePrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LivePrice) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *LivePrice) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Orderbook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock string            `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Bids  []*OrderbookEntry `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks  []*OrderbookEntry `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Body  string            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // Legacy: pipe-delimited text format
}

func (x *Orderbook) Reset() {
	*x = Orderbook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orderbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderbook) ProtoMessage() {}

func (x *Orderbook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderbook.ProtoReflect.Descriptor instead.
func (*Orderbook) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{4}
}

func (x *Orderbook) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *Orderbook) GetBids() []*OrderbookEntry {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Orderbook) GetAsks() []*OrderbookEntry {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *Orderbook) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type OrderbookEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume float64 `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Orders int32   `protobuf:"varint,3,opt,name=orders,proto3" json:"orders,omitempty"`
}

func (x *OrderbookEntry) Reset() {
	*x = OrderbookEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderbookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookEntry) ProtoMessage() {}

func (x *OrderbookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookEntry.ProtoReflect.Descriptor instead.
func (*OrderbookEntry) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{5}
}

func (x *OrderbookEntry) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderbookEntry) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OrderbookEntry) GetOrders() int32 {
	if x != nil {
		return x.Orders
	}
	return 0
}

// Pure protobuf orderbook (preferred)
type OrderBookBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockSymbol string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Bid         []*Bid                 `protobuf:"bytes,2,rep,name=bid,proto3" json:"bid,omitempty"`
	Offer       []*Offer               `protobuf:"bytes,3,rep,name=offer,proto3" json:"offer,omitempty"`
	Time        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *OrderBookBody) Reset() {
	*x = OrderBookBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderBookBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookBody) ProtoMessage() {}

func (x *OrderBookBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookBody.ProtoReflect.Descriptor instead.
func (*OrderBookBody) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{6}
}

func (x *OrderBookBody) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *OrderBookBody) GetBid() []*Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *OrderBookBody) GetOffer() []*Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *OrderBookBody) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Lot   float64 `protobuf:"fixed64,2,opt,name=lot,proto3" json:"lot,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{7}
}

func (x *Bid) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bid) GetLot() float64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

type Offer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Lot   float64 `protobuf:"fixed64,2,opt,name=lot,proto3" json:"lot,omitempty"`
}

func (x *Offer) Reset() {
	*x = Offer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{8}
}

func (x *Offer) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetLot() float64 {
	if x != nil {
		return x.Lot
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Response Wrapper
type WebsocketWrapMessageChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to MessageChannel:
	//
	//	*WebsocketWrapMessageChannel_RunningTrade
	//	*WebsocketWrapMessageChannel_Ping
	//	*WebsocketWrapMessageChannel_OrderbookBody
	//	*WebsocketWrapMessageChannel_RunningTradeBatch
	//	*WebsocketWrapMessageChannel_Liveprice
	//	*WebsocketWrapMessageChannel_Orderbook
	MessageChannel isWebsocketWrapMessageChannel_MessageChannel `protobuf_oneof:"message_channel"`
}

func (x *WebsocketWrapMessageChannel) Reset() {
	*x = WebsocketWrapMessageChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsocketWrapMessageChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketWrapMessageChannel) ProtoMessage() {}

func (x *WebsocketWrapMessageChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketWrapMessageChannel.ProtoReflect.Descriptor instead.
func (*WebsocketWrapMessageChannel) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{10}
}

func (m *WebsocketWrapMessageChannel) GetMessageChannel() isWebsocketWrapMessageChannel_MessageChannel {
	if m != nil {
		return m.MessageChannel
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetRunningTrade() *RunningTrade {
	if x, ok := x.GetMessageChannel().(*WebsocketWrapMessageChannel_RunningTrade); ok {
		return x.RunningTrade
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetPing() *PingResponse {
	if x, ok := x.GetMessageChannel().(*WebsocketWrapMessageChannel_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderbookBody() *OrderBookBody {
	if x, ok := x.GetMessageChannel().(*WebsocketWrapMessageChannel_OrderbookBody); ok {
		return x.OrderbookBody
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetRunningTradeBatch() *RunningTradeBatch {
	if x, ok := x.GetMessageChannel().(*WebsocketWrapMessageChannel_RunningTradeBatch); ok {
		return x.RunningTradeBatch
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetLiveprice() *LivePrice {
	if x, ok := x.GetMessageChannel().(*WebsocketWrapMessageChannel_Liveprice); ok {
		return x.Liveprice
	}
	return nil
}

func (x *WebsocketWrapMessageChannel) GetOrderbook() *Orderbook {
	if x, ok := x.GetMessageChannel().(*WebsocketWrapMessageChannel_Orderbook); ok {
		return x.Orderbook
	}
	return nil
}

type isWebsocketWrapMessageChannel_MessageChannel interface {
	isWebsocketWrapMessageChannel_MessageChannel()
}

type WebsocketWrapMessageChannel_RunningTrade struct {
	RunningTrade *RunningTrade `protobuf:"bytes,1,opt,name=running_trade,json=runningTrade,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Ping struct {
	Ping *PingResponse `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type WebsocketWrapMessageChannel_OrderbookBody struct {
	OrderbookBody *OrderBookBody `protobuf:"bytes,6,opt,name=orderbook_body,json=orderbookBody,proto3,oneof"` // Pure protobuf orderbook
}

type WebsocketWrapMessageChannel_RunningTradeBatch struct {
	RunningTradeBatch *RunningTradeBatch `protobuf:"bytes,8,opt,name=running_trade_batch,json=runningTradeBatch,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Liveprice struct {
	Liveprice *LivePrice `protobuf:"bytes,9,opt,name=liveprice,proto3,oneof"`
}

type WebsocketWrapMessageChannel_Orderbook struct {
	Orderbook *Orderbook `protobuf:"bytes,10,opt,name=orderbook,proto3,oneof"` // Hybrid orderbook (text body)
}

func (*WebsocketWrapMessageChannel_RunningTrade) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Ping) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_OrderbookBody) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_RunningTradeBatch) isWebsocketWrapMessageChannel_MessageChannel() {
}

func (*WebsocketWrapMessageChannel_Liveprice) isWebsocketWrapMessageChannel_MessageChannel() {}

func (*WebsocketWrapMessageChannel_Orderbook) isWebsocketWrapMessageChannel_MessageChannel() {}

// Request Messages
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{11}
}

func (x *PingRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WebsocketChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watchlist    []string `protobuf:"bytes,1,rep,name=watchlist,proto3" json:"watchlist,omitempty"`
	OrderBook    []string `protobuf:"bytes,2,rep,name=order_book,json=orderBook,proto3" json:"order_book,omitempty"`
	RunningTrade []string `protobuf:"bytes,3,rep,name=running_trade,json=runningTrade,proto3" json:"running_trade,omitempty"`
	// Note: tag 4 is likely reserved/unused
	RunningTradeBatch []string `protobuf:"bytes,5,rep,name=running_trade_batch,json=runningTradeBatch,proto3" json:"running_trade_batch,omitempty"`
	Liveprice         []string `protobuf:"bytes,6,rep,name=liveprice,proto3" json:"liveprice,omitempty"`
	OrderbookBody     []string `protobuf:"bytes,7,rep,name=orderbook_body,json=orderbookBody,proto3" json:"orderbook_body,omitempty"` // Subscribe to pure protobuf orderbook
}

func (x *WebsocketChannel) Reset() {
	*x = WebsocketChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsocketChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketChannel) ProtoMessage() {}

func (x *WebsocketChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketChannel.ProtoReflect.Descriptor instead.
func (*WebsocketChannel) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{12}
}

func (x *WebsocketChannel) GetWatchlist() []string {
	if x != nil {
		return x.Watchlist
	}
	return nil
}

func (x *WebsocketChannel) GetOrderBook() []string {
	if x != nil {
		return x.OrderBook
	}
	return nil
}

func (x *WebsocketChannel) GetRunningTrade() []string {
	if x != nil {
		return x.RunningTrade
	}
	return nil
}

func (x *WebsocketChannel) GetRunningTradeBatch() []string {
	if x != nil {
		return x.RunningTradeBatch
	}
	return nil
}

func (x *WebsocketChannel) GetLiveprice() []string {
	if x != nil {
		return x.Liveprice
	}
	return nil
}

func (x *WebsocketChannel) GetOrderbookBody() []string {
	if x != nil {
		return x.OrderbookBody
	}
	return nil
}

type WebsocketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel *WebsocketChannel `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Key     string            `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Ping    *PingRequest      `protobuf:"bytes,4,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *WebsocketRequest) Reset() {
	*x = WebsocketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datafeed_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketRequest) ProtoMessage() {}

func (x *WebsocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datafeed_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketRequest.ProtoReflect.Descriptor instead.
func (*WebsocketRequest) Descriptor() ([]byte, []int) {
	return file_proto_datafeed_proto_rawDescGZIP(), []int{13}
}

func (x *WebsocketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WebsocketRequest) GetChannel() *WebsocketChannel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *WebsocketRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WebsocketRequest) GetPing() *PingRequest {
	if x != nil {
		return x.Ping
	}
	return nil
}

var File_proto_datafeed_proto protoreflect.FileDescriptor

var file_proto_datafeed_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a,
	0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x22, 0xb8, 0x03,
	0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x41,
	0x0a, 0x0e, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0d, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x4f, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3a, 0x0a,
	0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x4c, 0x69,
	0x76, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x38, 0x0a,
	0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x38, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x61, 0x73, 0x6b,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x56, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0xc2, 0x01,
	0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x2b, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66,
	0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12,
	0x31, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f,
	0x74, 0x22, 0x2f, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x6f, 0x74, 0x22, 0x48, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xe0, 0x03, 0x0a,
	0x1b, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x57, 0x72, 0x61, 0x70, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x49, 0x0a, 0x0d,
	0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x12, 0x4c, 0x0a, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00,
	0x52, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x59, 0x0a, 0x13, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x48, 0x00, 0x52, 0x11, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3f, 0x0a, 0x09, 0x6c, 0x69,
	0x76, 0x65, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x48,
	0x00, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x42, 0x11, 0x0a, 0x0f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22,
	0x47, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xe9, 0x01, 0x0a, 0x10, 0x57, 0x65, 0x62,
	0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12,
	0x2e, 0x0a, 0x13, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x72, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x42, 0x6f, 0x64, 0x79, 0x22, 0xb6, 0x01, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x40, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x2a, 0x50, 0x0a,
	0x09, 0x54, 0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x52,
	0x41, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x55, 0x59, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x52,
	0x41, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x2a,
	0x60, 0x0a, 0x09, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16,
	0x42, 0x4f, 0x41, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x4f, 0x41, 0x52,
	0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x47, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x4f, 0x41, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x4e, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x47, 0x10,
	0x03, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x65, 0x6e, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2d, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x66, 0x65, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_datafeed_proto_rawDescOnce sync.Once
	file_proto_datafeed_proto_rawDescData = file_proto_datafeed_proto_rawDesc
)

func file_proto_datafeed_proto_rawDescGZIP() []byte {
	file_proto_datafeed_proto_rawDescOnce.Do(func() {
		file_proto_datafeed_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_datafeed_proto_rawDescData)
	})
	return file_proto_datafeed_proto_rawDescData
}

var file_proto_datafeed_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_datafeed_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_datafeed_proto_goTypes = []interface{}{
	(TradeType)(0),                      // 0: stockbit.datafeed.v1.TradeType
	(BoardType)(0),                      // 1: stockbit.datafeed.v1.BoardType
	(*Change)(nil),                      // 2: stockbit.datafeed.v1.Change
	(*RunningTrade)(nil),                // 3: stockbit.datafeed.v1.RunningTrade
	(*RunningTradeBatch)(nil),           // 4: stockbit.datafeed.v1.RunningTradeBatch
	(*LivePrice)(nil),                   // 5: stockbit.datafeed.v1.LivePrice
	(*Orderbook)(nil),                   // 6: stockbit.datafeed.v1.Orderbook
	(*OrderbookEntry)(nil),              // 7: stockbit.datafeed.v1.OrderbookEntry
	(*OrderBookBody)(nil),               // 8: stockbit.datafeed.v1.OrderBookBody
	(*Bid)(nil),                         // 9: stockbit.datafeed.v1.Bid
	(*Offer)(nil),                       // 10: stockbit.datafeed.v1.Offer
	(*PingResponse)(nil),                // 11: stockbit.datafeed.v1.PingResponse
	(*WebsocketWrapMessageChannel)(nil), // 12: stockbit.datafeed.v1.WebsocketWrapMessageChannel
	(*PingRequest)(nil),                 // 13: stockbit.datafeed.v1.PingRequest
	(*WebsocketChannel)(nil),            // 14: stockbit.datafeed.v1.WebsocketChannel
	(*WebsocketRequest)(nil),            // 15: stockbit.datafeed.v1.WebsocketRequest
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
}
var file_proto_datafeed_proto_depIdxs = []int32{
	16, // 0: stockbit.datafeed.v1.RunningTrade.websocket_time:type_name -> google.protobuf.Timestamp
	0,  // 1: stockbit.datafeed.v1.RunningTrade.action:type_name -> stockbit.datafeed.v1.TradeType
	16, // 2: stockbit.datafeed.v1.RunningTrade.time:type_name -> google.protobuf.Timestamp
	2,  // 3: stockbit.datafeed.v1.RunningTrade.change:type_name -> stockbit.datafeed.v1.Change
	1,  // 4: stockbit.datafeed.v1.RunningTrade.market_board:type_name -> stockbit.datafeed.v1.BoardType
	3,  // 5: stockbit.datafeed.v1.RunningTradeBatch.trades:type_name -> stockbit.datafeed.v1.RunningTrade
	2,  // 6: stockbit.datafeed.v1.LivePrice.change:type_name -> stockbit.datafeed.v1.Change
	16, // 7: stockbit.datafeed.v1.LivePrice.time:type_name -> google.protobuf.Timestamp
	7,  // 8: stockbit.datafeed.v1.Orderbook.bids:type_name -> stockbit.datafeed.v1.OrderbookEntry
	7,  // 9: stockbit.datafeed.v1.Orderbook.asks:type_name -> stockbit.datafeed.v1.OrderbookEntry
	9,  // 10: stockbit.datafeed.v1.OrderBookBody.bid:type_name -> stockbit.datafeed.v1.Bid
	10, // 11: stockbit.datafeed.v1.OrderBookBody.offer:type_name -> stockbit.datafeed.v1.Offer
	16, // 12: stockbit.datafeed.v1.OrderBookBody.time:type_name -> google.protobuf.Timestamp
	16, // 13: stockbit.datafeed.v1.PingResponse.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 14: stockbit.datafeed.v1.WebsocketWrapMessageChannel.running_trade:type_name -> stockbit.datafeed.v1.RunningTrade
	11, // 15: stockbit.datafeed.v1.WebsocketWrapMessageChannel.ping:type_name -> stockbit.datafeed.v1.PingResponse
	8,  // 16: stockbit.datafeed.v1.WebsocketWrapMessageChannel.orderbook_body:type_name -> stockbit.datafeed.v1.OrderBookBody
	4,  // 17: stockbit.datafeed.v1.WebsocketWrapMessageChannel.running_trade_batch:type_name -> stockbit.datafeed.v1.RunningTradeBatch
	5,  // 18: stockbit.datafeed.v1.WebsocketWrapMessageChannel.liveprice:type_name -> stockbit.datafeed.v1.LivePrice
	6,  // 19: stockbit.datafeed.v1.WebsocketWrapMessageChannel.orderbook:type_name -> stockbit.datafeed.v1.Orderbook
	16, // 20: stockbit.datafeed.v1.PingRequest.timestamp:type_name -> google.protobuf.Timestamp
	14, // 21: stockbit.datafeed.v1.WebsocketRequest.channel:type_name -> stockbit.datafeed.v1.WebsocketChannel
	13, // 22: stockbit.datafeed.v1.WebsocketRequest.ping:type_name -> stockbit.datafeed.v1.PingRequest
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_datafeed_proto_init() }
func file_proto_datafeed_proto_init() {
	if File_proto_datafeed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_datafeed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Change); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningTrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningTradeBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LivePrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orderbook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderbookEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderBookBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsocketWrapMessageChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsocketChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datafeed_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsocketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_datafeed_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*WebsocketWrapMessageChannel_RunningTrade)(nil),
		(*WebsocketWrapMessageChannel_Ping)(nil),
		(*WebsocketWrapMessageChannel_OrderbookBody)(nil),
		(*WebsocketWrapMessageChannel_RunningTradeBatch)(nil),
		(*WebsocketWrapMessageChannel_Liveprice)(nil),
		(*WebsocketWrapMessageChannel_Orderbook)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_datafeed_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_datafeed_proto_goTypes,
		DependencyIndexes: file_proto_datafeed_proto_depIdxs,
		EnumInfos:         file_proto_datafeed_proto_enumTypes,
		MessageInfos:      file_proto_datafeed_proto_msgTypes,
	}.Build()
	File_proto_datafeed_proto = out.File
	file_proto_datafeed_proto_rawDesc = nil
	file_proto_datafeed_proto_goTypes = nil
	file_proto_datafeed_proto_depIdxs = nil
}
